import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";
import ScrollRestorer from "@/components/ScrollRestorer";

export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Fixes Radix Dialog leaving overflow:hidden on body after navigation */}
            <ScrollRestorer />

            {/* Header */}
            <Header />

            {/* Main Content */}
            <main className="min-h-screen w-full pt-16">
              {children}
            </main>

            {/* Footer */}
            <footer className="bg-muted/50 py-12">
              <div className="container text-center text-grey-200 mx-auto px-4">
                <p>Made with ❤️ by Jignesh</p>
              </div>
            </footer>
            <Toaster richColors />
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}